export default [
    'title:carbon',
    'citation_id:"3327686"',
    'pub_key:US_5599670_A',
    'author:"Richard Jefferson" OR abstract:glucuronidase AND title:GUS',
    '"malaria vaccine" AND year_published:[1970 TO 1980]',
    'title:(leishmani* AND diagnos*) || abstract:(leishmani* AND diagnos*)',
    '"invalid field" AND ownar: "Microsoft Inc"',
    '"scholar" AND source.title: Nature',
    '"conflicting fields" AND source.title: Nature AND pub_key: 123',
    'classification detection AND "A61K38/00 C07K14/415 A01H5/10 C07K2319/00"',
    'abstract:(a OR b) && title:(c OR d)',
    // 'Most recent articles in Nature Journal',
    // 'Most patent citations for MeSH Term: "Glucuronidase"',
    // 'Query "malaria vaccine" with open access / fulltext',
    // 'Chemical "Sildenafil Citrate" with funding data, but no clinical trial data',
    // 'Subject Oncology with no funding data',
    // 'All Japanese publications between 1900 and 1930',
    // 'Author "Lipman DJ"',
    // 'Citation ID 3327686',
]
