export default [
    'title:glucuronidase',
    'pub_key:US_5599670_A',
    'author:"Richard Jefferson" OR abstract:glucuronidase AND title:GUS',
    '"malaria vaccine" AND year_published:[1970 TO 1980]',
    'title:(leishmani* AND diagnos*) || abstract:(leishmani* AND diagnos*) && classification:(A61K* OR C12N*)',
    '"scholar" AND source.title: Nature',
    'year_published: 1970 OR citation_id:"3327686"',
    '"A61K38/00 (5,328) C07K14/415 (4,749) A01H5/10 (4,610) C07K2319/00"',
    'abstract:(a OR b) && title:(c OR d)',
    // 'Most recent articles in Nature Journal',
    // 'Most patent citations for MeSH Term: "Glucuronidase"',
    // 'Query "malaria vaccine" with open access / fulltext',
    // 'Chemical "Sildenafil Citrate" with funding data, but no clinical trial data',
    // 'Subject Oncology with no funding data',
    // 'All Japanese publications between 1900 and 1930',
    // 'Author "Lipman DJ"',
    // 'Citation ID 3327686',
]
