// <div class="row">
//     <div v-for="color in colors" :style="{background: color.hex}" class="col">
//         {{color.key}}
//     </div>
// </div>

export default [
    { key: '$col-pri', hex: '#1b75bc', description: 'Primary Color' },
    { key: '$col-pri-2', hex: '#004767', description: 'Primary Color Hover' },
    { key: '$col-pri-3', hex: '#001e3c', description: 'Primary Color Focused' },
    { key: '$col-sec', hex: '#ffb300', description: 'Secondary Color' },
    { key: '$col-sec-2', hex: '#ff8800', description: 'Secondary Color Hover' },
    { key: '$col-ter', hex: '#5bb025', description: 'Tertiary Color' },
    { key: '$col-ter-2', hex: '#418e37', description: 'Tertiary Color Hover' },
    { key: '$col-qua', hex: '#ffffff', description: 'Quaternary Color' },
    { key: '$col-qua-txt', hex: '#a0a0a0', description: 'Quaternary Text Color' },
    { key: '$col-qua-2', hex: '#f1f1f1', description: 'Quaternary Color Hover' },
    { key: '$col-qua-3', hex: '#dadada', description: 'Quaternary Color border' },
    { key: '$col-meta', hex: '#808285', description: 'Meta Color 1' },
    { key: '$col-meta-2', hex: '#c5c5c5', description: 'Meta Color 2' },
    { key: '$col-cambia', hex: '#1f9cac', description: 'Cambia Reference Color ' },
    { key: '$col-cambia-2', hex: '#009098', description: 'Cambia Reference 2' },
    { key: '$col-black', hex: '#000000', description: 'Black Color ' },
    { key: '$col-white', hex: '#ffffff', description: 'White Color ' },
    { key: '$col-info', hex: '#1f9cac', description: 'Info Color ' },
    { key: '$col-info-bg', hex: '#f4fafb', description: 'Info Background Color ' },
    { key: '$col-success', hex: '#5bb025', description: 'Success Color ' },
    { key: '$col-success-bg', hex: '#f8fcf6', description: 'Success Background Color ' },
    { key: '$col-warning', hex: '#ffb300', description: 'Warning Color ' },
    { key: '$col-warning-bg', hex: '#fffbf2', description: 'Warning Background Color ' },
    { key: '$col-error', hex: '#d71920', description: 'Error Color ' },
    { key: '$col-error-2', hex: '#b10d28', description: 'Error Color Hover ' },
    { key: '$col-error-bg', hex: '#fdf3f4', description: 'Error Background Color ' },
    { key: '$col-meta-bio', hex: '#bb73ca', description: '' },
    { key: '$col-meta-inventor', hex: '#fb7c1f', description: '' },
    { key: '$col-meta-landscape', hex: '#b0c455', description: '' },
    { key: '$col-meta-notes', hex: '#8abbed', description: '' },
    { key: '$col-meta-collections', hex: '#d9c567', description: '' },
    { key: '$col-meta-public-collections', hex: '#c0a678', description: '' },
    { key: '$col-head-bg', hex: '#000', description: 'Header Background Color ' },
    { key: '$col-head-bg-2', hex: '#212121', description: 'Header Background Color Alt ' },
    { key: '$col-head-txt', hex: '#fff', description: 'Header Text Color ' },
    { key: '$col-head-a', hex: '#fff', description: 'Header Link Color ' },
    { key: '$col-head-a-hover', hex: '#7fa1bc', description: 'Header Link Hover Color ' },
    { key: '$col-head-borders', hex: '#313131', description: 'Header Borders Color ' },
    { key: '$col-field', hex: '#000000', description: 'Form + Field Text Color' },
    { key: '$col-field-bg', hex: '#fafafa', description: 'Form + Field Background Color' },
    { key: '$col-field-border', hex: '#dadada', description: 'Form + Field Border Color' },
    { key: '$col-field-focus', hex: '#78bd4c', description: 'Form + Field Focus Border Color' },
    { key: '$col-borders', hex: '#e4e4e4', description: 'Global Borders Color ' },
    { key: '$col-aside-bg', hex: '#f3f3f3', description: 'Global Sidebar background Color ' },
    { key: '$col-foot-bg', hex: '#fafafa', description: 'Footer Background Color ' },
    { key: '$col-foot-txt', hex: '#000', description: 'Footer Text Color ' },
    { key: '$col-foot-a', hex: '#000', description: 'Footer Link Color ' },
    { key: '$col-foot-a-hover', hex: '#1b75bc', description: 'Footer Link Hover Color ' },
    { key: '$col-foot-meta', hex: '#808285', description: 'Footer Meta Color ' },
    { key: '$col-baseline-bg', hex: '#000', description: 'Baseline Background Color ' },
    { key: '$col-baseline-txt', hex: '#fff', description: 'Baseline Text Color ' },
    { key: '$col-baseline-a', hex: '#fff', description: 'Baseline Link Color ' },
    { key: '$col-baseline-a-hover', hex: '#fff', description: 'Baseline Link Hover Color ' },
]
